spring.application.name=DATN_RentalCar-1
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

#spring.datasource.url=jdbc:sqlserver://localhost;databaseName=RentalCar_test
#spring.datasource.username=sa
#spring.datasource.password=123456
#spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
#
#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect
#spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true
#
#spring.security.user.name=u
#spring.security.user.password=u


spring.datasource.url= jdbc:sqlserver://localhost:1433;encrypt=true;trustServerCertificate=true;databaseName=rentalCar_test
spring.datasource.username=sa
spring.datasource.password=123456
server.servlet.session.timeout=55m
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.SQLServerDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto = none
logging.level.com.microsoft.sqlserver.jdbc==OFF
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

spring.web.resources.static-locations=file:./assets/images/,classpath:/static/

spring.web.resources.cache.cachecontrol.no-store=true
spring.web.resources.cache.period=0
spring.web.resources.chain.cache=false

#logging.level.org.springframework.web=DEBUG


spring.servlet.multipart.max-file-size=30MB
spring.servlet.multipart.max-request-size=30MB

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=thienptpd07675@fpt.edu.vn
spring.mail.password=y d o v f e o i j t s n m h z v
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
